name: nsp2022
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cpuonly=2.0
  - jupyter=1.0.0
  - matplotlib=3.5.3
  - numpy=1.23.4
  - pandas=1.5.1
  - pillow=9.2.0
  - pip=22.3.1
  - python=3.8.13
  - pytorch=1.13.0
  - scipy=1.9.3
  - stingray=1.1.1
  - torchaudio=0.13.0
  - torchvision=0.14.0
  - pip:
    - gpytorch==1.9.0
    - pyro-ppl==1.8.2
    - scikit-learn==1.1.3

